
# ------ ZIPKIN -------

- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: zipkin
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: dparra0007/iag-gbs-it-architecture-technical-architecture-trace-global:60241962
      from:
        kind: DockerImage
        name: dparra0007/iag-gbs-it-architecture-technical-architecture-trace-global:60241962
      generation: null
      importPolicy: {}
      name: "60241962"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: zipkin
  spec:
    replicas: 1
    selector:
      deploymentconfig: zipkin
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: zipkin
      spec:
        containers:
        - image: dparra0007/iag-gbs-it-architecture-technical-architecture-trace-global:60241962
          name: zipkin
          ports:
          - containerPort: 9411
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - zipkin
        from:
          kind: ImageStreamTag
          name: zipkin:60241962
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: zipkin
  spec:
    ports:
    - name: 9411-tcp
      port: 9411
      targetPort: 9411
    selector:
      deploymentconfig: zipkin
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: zipkin
  spec:
    to:
      kind: Service
      name: zipkin

# ------ ZIPKIN -------
