
# ------ ZUUL -------

- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: zuul
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: {{IMG_ZUUL_SERVICE}}:{{CI_TAG_ZUUL_SERVICE}}
      from:
        kind: DockerImage
        name: {{IMG_ZUUL_SERVICE}}:{{CI_TAG_ZUUL_SERVICE}}
      generation: null
      importPolicy: {}
      name: "{{CI_TAG_ZUUL_SERVICE}}"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: zuul
  spec:
    replicas: 1
    selector:
      deploymentconfig: zuul
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: zuul
      spec:
        containers:
        - image: {{IMG_ZUUL_SERVICE}}:{{CI_TAG_ZUUL_SERVICE}}
          name: zuul
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: "2"
              memory: "2Gi"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - zuul
        from:
          kind: ImageStreamTag
          name: zuul:{{CI_TAG_ZUUL_SERVICE}}
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: zuul
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: zuul
  status:
    loadBalancer: {}

# ------ ZUUL -------
