FROM iagtech/dredd:1.0.0-public

RUN apk update && apk add ca-certificates && update-ca-certificates && apk add openssl

RUN mkdir -p /usr/src/app && \
    addgroup -g 1000 -S username && \
    adduser -u 1001 -S username -G username -h /usr/src/app -s /sbin/nologin && \
    chown -R 1001:0 /usr/src/app && chmod -R og+rwx /usr/src/app

WORKDIR /usr/src/app

USER 1001

CMD ["/bin/sh", "-c", "sleep 2m && apiary fetch --api-name=glplambdaairairports --output=swagger.yaml && dredd ./swagger.yaml http://airports:8080/ -r apiary -j apiaryApiKey:bf50f24bdfc3dd2c747dc3c429b2b989 -j apiaryApiName:glplambdaairairports"]